
variables:
  GOBIN:  "$(GOPATH)/bin" # Go binaries path
  GOPATH: "$(system.defaultWorkingDirectory)/gopath" # Go workspace path
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)" # Path to the module"s code

jobs:
- job: Linux
  pool:
    vmImage: "ubuntu-16.04"
  strategy:
    matrix:
    # Postgres
      go 1.12 (on) postgres:
        go_version: "1.12"
        GO111MODULE: "on"
        SODA_DIALECT: "postgres"
      go 1.12 (off) postgres:
        go_version: "1.12"
        GO111MODULE: "off"
        SODA_DIALECT: "postgres"
      go 1.13 (on) postgres:
        go_version: "1.13"
        GO111MODULE: "on"
        SODA_DIALECT: "postgres"
      go 1.13 (off) postgres:
        go_version: "1.13"
        GO111MODULE: "off"
        SODA_DIALECT: "postgres"
    # Cockroach
      go 1.13 (on) cockroach:
        go_version: "1.13"
        GO111MODULE: "on"
        SODA_DIALECT: "cockroach"
      go 1.13 (off) cockroach:
        go_version: "1.13"
        GO111MODULE: "off"
        SODA_DIALECT: "cockroach"
    # MySQL
      go 1.13 (on) mysql:
        go_version: "1.13"
        GO111MODULE: "on"
        SODA_DIALECT: "mysql"
        MYSQL_PORT: "3307"
      go 1.13 (off) mysql:
        go_version: "1.13"
        GO111MODULE: "off"
        SODA_DIALECT: "mysql"
        MYSQL_PORT: "3307"
  steps:
    - template: azure-tests.yml